export const SEED_VEHICLES = [
  {
    id: "auto-01",
    nombre: "Toyota Hilux SRX 4x4",
    marca: "Toyota",
    modelo: "Hilux SRX",
    anio: 2024,
    precio: 45000,
    categoria: "autos",
    tipoCombustible: "Diésel",
    transmision: "Automática",
    kilometraje: 12000,
    condicion: "usado",
    ubicacion: "Santiago, Centro",
    imagenPrincipal: "/vehicles/auto-01.jpg",
    imagenes: [
      "/vehicles/auto-01.jpg",
      "/vehicles/auto-01.jpg"
    ],
    descripcion: "La camioneta pick-up líder en confiabilidad. Versión SRX tope de gama con tracción 4x4, asientos de cuero con ventilación, sistema de audio premium JBL, y el motor diésel 2.8L turbo de alta durabilidad.",
    destacado: true,
    estado: "disponible",
    especificaciones: {
      "Motor": "2.8L Turbo Diésel",
      "Potencia": "204 HP",
      "Torque": "500 Nm",
      "Tracción": "4x4 acoplable con reductora",
      "Consumo promedio": "11.5 km/l",
      "Capacidad de carga": "1,000 kg"
    },
    fechaIngreso: "2026-05-10"
  },
  {
    id: "auto-02",
    nombre: "Mazda 3 Hatchback Sport",
    marca: "Mazda",
    modelo: "Mazda 3",
    anio: 2023,
    precio: 170000,
    moneda: "BOB",
    categoria: "autos",
    tipoCombustible: "Gasolina",
    transmision: "Manual",
    kilometraje: 18500,
    condicion: "usado",
    ubicacion: "Valparaíso, Viña del Mar",
    imagenPrincipal: "/vehicles/auto-02.jpg",
    imagenes: [
      "/vehicles/auto-02.jpg",
      "/vehicles/auto-02.jpg"
    ],
    descripcion: "Diseño exterior Kodo dinámico y elegante. Interior premium que rivaliza con marcas de lujo. Motor SkyActiv-G 2.0L con excelente eficiencia y una conducción ágil y deportiva en cada curva.",
    destacado: true,
    estado: "disponible",
    especificaciones: {
      "Motor": "2.0L SkyActiv-G",
      "Potencia": "153 HP",
      "Torque": "200 Nm",
      "Tracción": "Delantera (FWD)",
      "Capacidad de maletero": "358 litros",
      "Equipamiento": "Pantalla 8.8\", Apple CarPlay/Android Auto, Control crucero adaptativo"
    },
    fechaIngreso: "2026-06-15"
  },
  {
    id: "auto-03",
    nombre: "Ford Mustang GT Premium",
    marca: "Ford",
    modelo: "Mustang GT",
    anio: 2022,
    precio: 52000,
    categoria: "autos",
    tipoCombustible: "Gasolina",
    transmision: "Automática",
    kilometraje: 9000,
    condicion: "usado",
    ubicacion: "Santiago, Las Condes",
    imagenPrincipal: "/vehicles/auto-03.jpg",
    imagenes: [
      "/vehicles/auto-03.jpg",
      "/vehicles/auto-03.jpg"
    ],
    descripcion: "El icónico muscle car americano. Motor V8 Coyote 5.0L que rinde tributo a la potencia. Versión GT Premium equipada con escapes activos, amortiguadores MagneRide, pantallas digitales configurables y asientos deportivos calefaccionados.",
    destacado: true,
    estado: "reservado",
    especificaciones: {
      "Motor": "5.0L V8 Coyote",
      "Potencia": "460 HP",
      "Torque": "569 Nm",
      "Tracción": "Trasera (RWD)",
      "Aceleración 0-100 km/h": "4.3 segundos",
      "Transmisión": "Automática de 10 velocidades"
    },
    fechaIngreso: "2026-04-01"
  },
  {
    id: "moto-01",
    nombre: "Honda CB500X",
    marca: "Honda",
    modelo: "CB500X Adventure",
    anio: 2024,
    precio: 8900,
    categoria: "motos",
    tipoCombustible: "Gasolina",
    transmision: "Manual",
    kilometraje: 0,
    condicion: "nuevo",
    ubicacion: "Santiago, Las Condes",
    imagenPrincipal: "/vehicles/moto-01.jpg",
    imagenes: [
      "/vehicles/moto-01.jpg",
      "/vehicles/moto-01.jpg"
    ],
    descripcion: "La moto de aventura definitiva para el carnet A2. Equipada con horquilla invertida Showa SFF-BP de 41 mm, doble disco delantero con pinzas Nissin y una ergonomía excelente para viajes largos o desplazamientos diarios en la ciudad.",
    destacado: true,
    estado: "disponible",
    especificaciones: {
      "Motor": "Bicilíndrico en paralelo, 471cc",
      "Potencia": "47 HP @ 8600 rpm",
      "Torque": "43 Nm @ 6500 rpm",
      "Peso en orden de marcha": "199 kg",
      "Capacidad del tanque": "17.5 Litros",
      "Frenos": "Doble disco delantero 296mm con ABS"
    },
    fechaIngreso: "2026-07-01"
  },
  {
    id: "moto-02",
    nombre: "Yamaha MT-09 Hyper Naked",
    marca: "Yamaha",
    modelo: "MT-09",
    anio: 2023,
    precio: 13200,
    categoria: "motos",
    tipoCombustible: "Gasolina",
    transmision: "Manual",
    kilometraje: 4200,
    condicion: "usado",
    ubicacion: "Concepción, Centro",
    imagenPrincipal: "/vehicles/moto-02.jpg",
    imagenes: [
      "/vehicles/moto-02.jpg",
      "/vehicles/moto-02.jpg"
    ],
    descripcion: "Despierta tu lado oscuro con la Yamaha MT-09. Su motor tricilíndrico CP3 de 890 cc ofrece un torque explosivo instantáneo. Equipada con Quickshifter bidireccional, IMU de 6 ejes con ayudas electrónicas avanzadas y diseño agresivo.",
    destacado: false,
    estado: "disponible",
    especificaciones: {
      "Motor": "Tricilíndrico CP3, 890cc",
      "Potencia": "119 HP @ 10,000 rpm",
      "Torque": "93 Nm @ 7000 rpm",
      "Electrónica": "TCS, SCS, LIF y ABS en curvas",
      "Peso": "189 kg",
      "Transmisión": "6 velocidades con embrague antirrebote y Quickshifter"
    },
    fechaIngreso: "2026-05-20"
  },
  {
    id: "moto-03",
    nombre: "BMW R 1250 GS Adventure",
    marca: "BMW",
    modelo: "R 1250 GS Adventure",
    anio: 2024,
    precio: 29500,
    categoria: "motos",
    tipoCombustible: "Gasolina",
    transmision: "Manual",
    kilometraje: 1500,
    condicion: "usado",
    ubicacion: "Santiago, Las Condes",
    imagenPrincipal: "/vehicles/moto-03.jpg",
    imagenes: [
      "/vehicles/moto-03.jpg",
      "/vehicles/moto-03.jpg"
    ],
    descripcion: "La reina indiscutible del turismo de aventura. Motor bóxer de 1254 cc con distribución variable ShiftCam. Edición Adventure con tanque de combustible de 30L, defensas completas de motor y maletas laterales de aluminio incluidas.",
    destacado: true,
    estado: "disponible",
    especificaciones: {
      "Motor": "Bóxer bicilíndrico con ShiftCam, 1254cc",
      "Potencia": "136 HP @ 7750 rpm",
      "Torque": "143 Nm @ 6250 rpm",
      "Transmisión": "Cardán con asistente de cambios Pro",
      "Capacidad del tanque": "30 Litros",
      "Equipamiento": "Pantalla TFT Connectivity, luces adaptativas, modos de conducción Pro"
    },
    fechaIngreso: "2026-06-25"
  },
  {
    id: "maquinaria-01",
    nombre: "Excavadora Caterpillar 320 GC",
    marca: "Caterpillar",
    modelo: "320 GC",
    anio: 2023,
    precio: 125000,
    categoria: "transporte_pesado",
    tipoCombustible: "Diésel",
    transmision: "Hidrostática",
    kilometraje: 2400,
    condicion: "usado",
    ubicacion: "Antofagasta, Sector Industrial",
    imagenPrincipal: "/vehicles/maquinaria-01.jpg",
    imagenes: [
      "/vehicles/maquinaria-01.jpg",
      "/vehicles/maquinaria-01.jpg"
    ],
    descripcion: "La excavadora Caterpillar 320 GC equilibra perfectamente el rendimiento con funciones de costo de operación y combustible reducido. Ideal para aplicaciones de excavación ligera a mediana con una cabina confortable y segura.",
    destacado: true,
    estado: "disponible",
    especificaciones: {
      "Motor": "Cat C4.4 ACERT",
      "Potencia neta": "145 HP",
      "Peso operativo": "20,500 kg",
      "Capacidad de balde": "1.2 m³",
      "Profundidad máx. excavación": "6.72 metros",
      "Horas de uso": "2,400 horas"
    },
    fechaIngreso: "2026-03-10"
  },
  {
    id: "maquinaria-02",
    nombre: "Tractor John Deere 6150J",
    marca: "John Deere",
    modelo: "6150J",
    anio: 2022,
    precio: 88000,
    categoria: "maquinaria_agricola",
    tipoCombustible: "Diésel",
    transmision: "Mecánica Sincronizada",
    kilometraje: 3100,
    condicion: "usado",
    ubicacion: "Rancagua, Agrícola",
    imagenPrincipal: "/vehicles/maquinaria-02.jpg",
    imagenes: [
      "/vehicles/maquinaria-02.jpg",
      "/vehicles/maquinaria-02.jpg"
    ],
    descripcion: "Fuerza y versatilidad agrícola incomparable. El tractor John Deere 6150J ofrece tracción 4x4, cabina presurizada de alta comodidad y la legendaria durabilidad de los motores John Deere para trabajos pesados en el campo.",
    destacado: false,
    estado: "disponible",
    especificaciones: {
      "Motor": "John Deere 6.8L de 6 cilindros",
      "Potencia": "150 HP",
      "Tracción": "4WD doble tracción",
      "Toma de fuerza (TDP)": "125 HP @ 1000/540 rpm",
      "Transmisión": "PowrQuad 16x16 marchas",
      "Horas de uso": "3,100 horas"
    },
    fechaIngreso: "2026-04-18"
  },
  {
    id: "maquinaria-03",
    nombre: "Retroexcavadora JCB 3CX Eco",
    marca: "JCB",
    modelo: "3CX Eco",
    anio: 2024,
    precio: 96500,
    categoria: "maquinaria_agricola",
    tipoCombustible: "Diésel",
    transmision: "Powershift",
    kilometraje: 0,
    condicion: "nuevo",
    ubicacion: "Santiago, San Bernardo",
    imagenPrincipal: "/vehicles/maquinaria-03.jpg",
    imagenes: [
      "/vehicles/maquinaria-03.jpg",
      "/vehicles/maquinaria-03.jpg"
    ],
    descripcion: "La retroexcavadora número uno del mundo. Diseñada para ofrecer máxima eficiencia de combustible, bajos costos operativos, excelente rendimiento en excavación y empuje, y cabina con aire acondicionado y controles ergonómicos.",
    destacado: true,
    estado: "disponible",
    especificaciones: {
      "Motor": "JCB EcoMAX",
      "Potencia": "74 HP",
      "Peso operativo": "8,135 kg",
      "Tracción": "4x4 automática",
      "Capacidad pala delantera": "1.0 m³",
      "Profundidad máx. excavación retro": "4.75 metros"
    },
    fechaIngreso: "2026-07-05"
  },
  {
    id: "auto-ev-01",
    nombre: "Tesla Model 3 Highland",
    marca: "Tesla",
    modelo: "Model 3 Highland",
    anio: 2024,
    precio: 42500,
    categoria: "autos_electricos",
    tipoCombustible: "Eléctrico",
    transmision: "Automática",
    kilometraje: 0,
    condicion: "nuevo",
    ubicacion: "La Paz, Zona Sur",
    imagenPrincipal: "/vehicles/auto-ev-01.jpg",
    imagenes: ["/vehicles/auto-ev-01.jpg",
      "/vehicles/auto-ev-01.jpg"
    ],
    descripcion: "El Tesla Model 3 Highland redefinió la berlina eléctrica con mayor autonomía, insonorización de primer nivel y un interior ultra minimalista con pantalla trasera para pasajeros. Aceleración instantánea y tecnología Autopilot.",
    destacado: true,
    estado: "disponible",
    especificaciones: {
      "Motor": "Eléctrico Dual Motor",
      "Autonomía": "629 km (WLTP)",
      "Aceleración 0-100 km/h": "4.4 segundos",
      "Velocidad máxima": "201 km/h",
      "Batería": "75 kWh LFP",
      "Tracción": "AWD integral"
    },
    fechaIngreso: "2026-07-20",
    telefonoContacto: "59177490451"
  },
  {
    id: "moto-ev-01",
    nombre: "Harley-Davidson LiveWire One",
    marca: "Harley-Davidson",
    modelo: "LiveWire One",
    anio: 2024,
    precio: 21900,
    categoria: "motos_electricos",
    tipoCombustible: "Eléctrico",
    transmision: "Automática",
    kilometraje: 150,
    condicion: "usado",
    ubicacion: "Santa Cruz, Equipetrol",
    imagenPrincipal: "/vehicles/moto-ev-01.jpg",
    imagenes: ["/vehicles/moto-ev-01.jpg",
      "/vehicles/moto-ev-01.jpg"
    ],
    descripcion: "La primera motocicleta 100% eléctrica de Harley-Davidson bajo la submarca LiveWire. Aceleración brutal sin embrague ni marchas, 0 a 100 en solo 3 segundos. Sonido futurista característico y conectividad integrada.",
    destacado: true,
    estado: "disponible",
    especificaciones: {
      "Motor": "Revelation PMAC",
      "Potencia": "100 HP",
      "Torque": "117 Nm instantáneo",
      "Autonomía urbana": "235 km",
      "Carga rápida DC": "0-100% en 60 min",
      "Modos de conducción": "7 modos (4 predefinidos, 3 personalizados)"
    },
    fechaIngreso: "2026-07-22",
    telefonoContacto: "59176543210"
  }
];
